services:
  # The Flask App
  web:
    build:
      context: .
      args:
        - APP_NAME=cerberus
    image: cerberus-api
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: db 
      MYSQL_USER: blendata
      MYSQL_PASSWORD: "#########"
      MYSQL_DATABASE: auth
    depends_on:
      db:
        condition: service_healthy

  # The MySQL Database
  db:
    image: cerberus-db
    build:
      context: .
      dockerfile_inline: |
        FROM mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "#########"
      MYSQL_DATABASE: auth
      MYSQL_USER: blendata
      MYSQL_PASSWORD: "#########"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p'#########'"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  # PostgreSQL for MLflow Metadata
  pg-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: blendata
      POSTGRES_PASSWORD: "#########"
      POSTGRES_DB: mlflow
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blendata -d mlflow"]
      interval: 5s
      timeout: 5s
      retries: 5

  # MLflow Tracking Server
  mlflow:
    build: .
    container_name: mlflow_server
    restart: always
    ports:
      - "5050:5000"
    environment:
      - BACKEND_STORE_URI=postgresql://blendata:#########@pg-db:5432/mlflow
    command: >
      mlflow server 
      --backend-store-uri postgresql://blendata:#########@pg-db:5432/mlflow
      --host 0.0.0.0
      --port 5000
      --serve-artifacts
      --default-artifact-root mlflow-artifacts:/
    depends_on:
      pg-db:
        condition: service_healthy

  # ML Studio Backend
  ml_studio:
    build:
      context: .
      args:
        - APP_NAME=ml_studio
    image: ml_studio
    container_name: ml_studio
    ports:
      - "5001:5000"

volumes:
  mysql_data:
  pg_data: